### ISSUE TITLE
Misc Icons to Add

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/images#15]
- [ ] [pgadmin4](https://hub.docker.com/r/dpage/pgadmin4/)
- [ ] [pgbackups](https://hub.docker.com/r/prodrigestivill/postgres-backup-local/tags) aka `postgres-backup-local`
- [ ] [plexautolang](https://hub.docker.com/r/remirigal/plex-auto-languages) aka `plex-auto-languages`
- [ ] [swag](https://docs.linuxserver.io/images/docker-swag/)

**Comment by davidnewhall** [comment]
make a pr

**Comment by angrycuban13** [comment]
@bakerboy448 seriously come on man
